AWSTemplateFormatVersion: '2010-09-09'
Description: FSS EventBridge Rule Pattern to Send to Main Scanner Region EventBus. If you delete this stack eventbridge wont send events for FSS to scan.
Parameters:
  SourceRegionEventBusARN:
    Type: String
    Description: ARN of the Event bus in a different account or region
Resources:
  FSSEventBridgeRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: FSSEventBridgeRule
      EventPattern:
        source:
          - 'aws.s3'
        detail-type:
          - 'Object Created'
      Targets:
        - Arn: !Join [":", ["arn", "aws", "events", !Ref SourceRegionEventBusARN, !Ref "AWS::AccountId", "event-bus/default"]]
          Id: FSSEventBusTarget
          RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/FSS-EventBridge-Role"

Outputs:
  EventBridgeRuleName:
    Value: !Ref FSSEventBridgeRule
    Description: Name of the created EventBridge rule
  EventBridgeRuleARN:
    Value: !GetAtt FSSEventBridgeRule.Arn
    Description: ARN of the created EventBridge rule
