AWSTemplateFormatVersion: '2010-09-09'
Description: FSS IAM Role for EventBridge to send events to Main Scanner Region EventBus. If deleted, permissions to send events to target will be gone.
Resources:
  EventBridgeIAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: FSS-EventBridge-Role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: [events.amazonaws.com]
              Action: ["sts:AssumeRole"]
        Policies:
          - PolicyName: MyPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: ["events:PutEvents"]
                  Resource: !Join [":", ["arn", "aws", "events", !Ref "AWS::Region", !Ref "AWS::AccountId", "event-bus/default"]]

Outputs:
  EventBridgeIAMRoleARN:
      Value: !GetAtt EventBridgeIAMRole.Arn
  SourceRegionEventBusARN:
      Value: !Join [":", ["arn", "aws", "events", !Ref "AWS::Region", !Ref "AWS::AccountId", "event-bus/default"]]